version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: udd_mysql_prod
    restart: always
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - dbdata_prod:/var/lib/mysql 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build: ./server
    container_name: udd_server_prod
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "mysql://appuser:apppass@db:3306/appdb" 
      PORT: "4000"
      NODE_ENV: "production"
    command: sh -c "npm run prisma:deploy && npm run start" 
    ports:
      - "4001:4000" 

  web:
    build:
      context: ./web
      args:
        # Usa http://TU_IP_PUBLICA_AWS:4001 (o tu dominio si lo tienes)
        - VITE_API_URL=http://18.191.239.111:4001
    container_name: udd_web_prod
    restart: always
    depends_on:
      - server
    ports:
      - "80:80"

volumes:
  dbdata_prod: 