services:
  # 1. BASE DE DATOS (Igual que antes)
  db:
    image: mysql:8.0
    container_name: udd_mysql_prod
    restart: always
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - dbdata_prod:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. BACKEND (Servidor API)
  server:
    build: ./server
    container_name: udd_server_prod
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "mysql://appuser:apppass@db:3306/appdb"
      PORT: "4000"
      NODE_ENV: "production"
    ports:
      - "4001:4000"  # La API escuchará en el puerto 4001 de AWS
    command: sh -c "npx prisma migrate deploy && node dist/index.js"

  # 3. FRONTEND (Tu Página Web) - ¡NUEVO!
  web:
    build:
      context: ./web
      args:
        # ¡OJO! Aquí pondrás la IP de tu AWS cuando la tengas
        - VITE_API_URL=http://TU_IP_PUBLICA_AWS:4001/api
    container_name: udd_web_prod
    restart: always
    ports:
      - "80:80"  # La web escuchará en el puerto normal de internet (HTTP)

volumes:
  dbdata_prod: