version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: udd_mysql_prod
    restart: always
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - dbdata_prod:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build: ./server
    container_name: udd_server_prod
    restart: always
    depends_on:
      - db
    ports:
      - "4001:4000"
      - "5556:5555"
    environment:
      DATABASE_URL: "mysql://appuser:apppass@db:3306/appdb"
      PORT: "4000"
      NODE_ENV: "production"
    command: sh -c "npm run start"

  web:
    build:
      context: ./web
      args:
        - VITE_API_URL=http://18.221.120.112:4001
    container_name: udd_web_prod
    restart: always
    depends_on:
      - server
    ports:
      - "80:80"

volumes:
  dbdata_prod:
